### ISSUE TITLE
view

### ISSUE THREAD

**Issue by PixieTheKitsune** [Gakuto1112/CatMaid#2]
so i got the model and i am using on a origins server where my player size is set to 0.40 (1 = normal size) and whenever i scale the model smaller with eye view locked on it the view point always goes way to far either up or down. could this please be fixed? its really ruining my experience.

**Comment by Gakuto1112** [comment]
Do you mean that when the position of the first person camera position is changed, the position of the cross hairs on the screen and the selected block are misaligned?

![Image](https://user-images.githubusercontent.com/90630001/173267151-bf11eace-35b5-4527-989a-490c5a91133b.jpg)

This is a Figura specification. No one can change this. 

> Please keep in mind that this change does not affect where the crosshair really is, so if you move the camera, and try to break a block, the block will still break in the same place it would usually do
From [Figura wiki](https://github.com/Moonlight-MC/Figura/wiki/Camera-API)

**Comment by Gakuto1112** [comment]
The latest version of this avatar does not support resizing. However, the version for a request previously created supports resizing. It is not compatible with the latest version.
https://github.com/Gakuto1112/CatMaid/tree/Request-Felicia

**Comment by PixieTheKitsune** [comment]
i can send you a few screenshots of what i mean in a few hours, cause i get that the crosshair is misaligned cause of it not being able to change hitbox

**Comment by Gakuto1112** [comment]
カメラの位置を移動させても、クロスヘアの位置が変化しないのはFiguraの仕様です。

> Please keep in mind that this change does not affect where the crosshair really is, so if you move the camera, and try to break a block, the block will still break in the same place it would usually do
From [Figura wiki](https://github.com/Moonlight-MC/Figura/wiki/Camera-API)

**Comment by Gakuto1112** [comment]
カメラの位置を移動させても、クロスヘアの位置が変化しないのはFiguraの仕様です。

> Please keep in mind that this change does not affect where the crosshair really is, so if you move the camera, and try to break a block, the block will still break in the same place it would usually do
From [Figura wiki](https://github.com/Moonlight-MC/Figura/wiki/Camera-API)
